<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="aulae205-21" ignored="0" name="Default test" tests="10" failures="1" timestamp="16 ago 2017 01:58:56 GMT" time="0.052" errors="0">
  <testcase name="debeDividirCorrectamente" time="0.008" classname="co.unbosque.isii.calculadora_pruebas.NewTest"/>
  <testcase name="debeMultiplicarCorrectamente" time="0.002" classname="co.unbosque.isii.calculadora_pruebas.NewTest"/>
  <testcase name="debeRestarCorrectamente" time="0.001" classname="co.unbosque.isii.calculadora_pruebas.NewTest"/>
  <testcase name="debeSumarCorrectamente" time="0.001" classname="co.unbosque.isii.calculadora_pruebas.NewTest"/>
  <testcase name="laOperacionDivisionExiste" time="0.001" classname="co.unbosque.isii.calculadora_pruebas.NewTest"/>
  <testcase name="laOperacionMultiplicacionExiste" time="0.001" classname="co.unbosque.isii.calculadora_pruebas.NewTest"/>
  <testcase name="laOperacionRestaExiste" time="0.0" classname="co.unbosque.isii.calculadora_pruebas.NewTest"/>
  <testcase name="laOperacionSumaExiste" time="0.001" classname="co.unbosque.isii.calculadora_pruebas.NewTest"/>
  <testcase name="laSeparacionDeNumerosExiste" time="0.002" classname="co.unbosque.isii.calculadora_pruebas.NewTest"/>
  <testcase name="laSeparacionDeOperadoresExiste" time="0.002" classname="co.unbosque.isii.calculadora_pruebas.NewTest">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;-&amp;gt; but was:&amp;lt;&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<-> but was:<>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at co.unbosque.isii.calculadora_pruebas.NewTest.laSeparacionDeOperadoresExiste(NewTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- laSeparacionDeOperadoresExiste -->
</testsuite> <!-- Default test -->
